### ISSUE TITLE
ModuleNotFoundError: No module named 'l2cat'

### ISSUE THREAD

**Issue by leixyou** [fO-000/bluescan#11]
Traceback (most recent call last):
  File "/home/ubuntu/bluetooth/pybluescan/bin/bluescan", line 5, in <module>
    from bluescan.__main__ import main
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/bluescan/__main__.py", line 17, in <module>
    from .ui import parse_cmdline
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/bluescan/ui.py", line 56, in <module>
    from btgatt import service_names, charac_names, descriptor_names
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/btgatt/__init__.py", line 6, in <module>
    from btatt import Attribute
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/btatt/__init__.py", line 7, in <module>
    from l2cat.l2cap_client import L2CAPClient
ModuleNotFoundError: No module named 'l2cat'

There is no l2cat library can be installed.

I noted that the btatt library was updated on April 30. 
Maybe due to the btatt library update?

**Comment by fO-000** [comment]
Thank you for opening this issue.

This problem is because I imported `l2cat` into `btatt` prematurely. `btatt` and `bluescan` currently do not need `l2cat`.

I have released the new version `0.0.2` for `btatt` with `l2cat` commented out.
Try this version to see if the problem can be solved.

**Comment by leixyou** [comment]
bluescan version 0.6.3
btatt version 0.0.2
bluescan -h
Traceback (most recent call last):
  File "/home/ubuntu/bluetooth/pybluescan/bin/bluescan", line 5, in <module>
    from bluescan.__main__ import main
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/bluescan/__main__.py", line 19, in <module>
    from .br_scan import BRScanner
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/bluescan/br_scan.py", line 31, in <module>
    from .common import bdaddr_to_company_name
  File "/home/ubuntu/bluetooth/pybluescan/lib/python3.6/site-packages/bluescan/common.py", line 28, in <module>
    company_id = items[0].removesuffix('   (hex)')
AttributeError: 'str' object has no attribute 'removesuffix'

Still exist below error when i run bluescan.

**Comment by fO-000** [comment]
The `removesuffix()` is new in Python3.9. However, you used python3.6.

Please upgrade your python or use a lower version bluescan.

**Comment by wiggigemc489** [comment]
hey, im having the same problem trying to run bluescan, i had issues with building pybluez but managed fixing them and now after i finally managed to install blue scan i only get this output:
Traceback (most recent call last):
  File "/home/wiggige/.local/bin/bluescan", line 5, in <module>
    from bluescan.__main__ import main
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/__main__.py", line 19, in <module>
    from .br_scan import BRScanner
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/br_scan.py", line 31, in <module>
    from .common import bdaddr_to_company_name
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/common.py", line 28, in <module>
    company_id = items[0].removesuffix('   (hex)')
AttributeError: 'str' object has no attribute 'removesuffix'


tried installing also python3.9 but seems like my python is up to date. any idea?
