### ISSUE TITLE
虚拟环境中运行bluescan报错

### ISSUE THREAD

**Issue by xilymen** [fO-000/bluescan#13]
报错信息如下：
(virtualenv_bluescan) root@xilymen:~# bluescan
Traceback (most recent call last):
  File "/root/.vertualenvs/virtualenv_bluescan/bin/bluescan", line 5, in <module>
    from bluescan.__main__ import main
  File "/root/.vertualenvs/virtualenv_bluescan/lib/python3.9/site-packages/bluescan/__main__.py", line 21, in <module>
    from .gatt_scan import GATTScanner
  File "/root/.vertualenvs/virtualenv_bluescan/lib/python3.9/site-packages/bluescan/gatt_scan.py", line 23, in <module>
    from .common import BLUEZ_NAME, mainloop
  File "/root/.vertualenvs/virtualenv_bluescan/lib/python3.9/site-packages/bluescan/common.py", line 4, in <module>
    from gi.repository import GObject
ModuleNotFoundError: No module named 'gi'

**Comment by fO-000** [comment]
如果在虚拟环境中运行，发行版管理的依赖 package 需要让虚拟环境的 pip 管理。

**Comment by xilymen** [comment]
好的，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sourcell Xu ***@***.***&gt;
发送时间: 2021年5月19日 13:32
收件人: fO-000/bluescan ***@***.***&gt;
抄送: xilymen ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[fO-000/bluescan] 虚拟环境中运行bluescan报错 (#13)





 
如果在虚拟环境中运行，发行版管理的依赖 package 需要让虚拟环境的 pip 管理。
